<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <RootNamespace>Foreman.Monitor</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Foreman.Core\Foreman.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" />
    <PackageReference Include="System.Diagnostics.EventLog" />
    <PackageReference Include="Microsoft.Diagnostics.Tracing.TraceEvent" />
  </ItemGroup>

</Project>
